### ISSUE TITLE
ValueError: day is out of range for month

### ISSUE THREAD

**Issue by Justintime50** [hacktoolkit/phablytics#8]
I'm getting the following for the date 2021/05/07 - I ran the following in the repl and was able to reproduce the issue:

```python
>> import calendar
>>> import datetime
>>> y, m, d = dt.year, dt.month, dt.day
>>> dt = datetime.date(2021, 5, 31) - datetime.timedelta(days=360). # this is what the logic does
>>> y, m, d = dt.year, dt.month, dt.day
>>> datetime.date(y, m, calendar.monthrange(y, m)[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: day is out of range for mont
```

Here is the error though:

![Screen Shot 2021-05-07 at 12 06 58 PM](https://user-images.githubusercontent.com/39606064/117491094-f93edb00-af2c-11eb-9780-49dd8954f04c.png)

**Comment by Justintime50** [comment]
After poking a bit, I can only assume these should have been `365` days instead of `360`? This seems to clear it up in the repl:

https://github.com/hacktoolkit/phablytics/blob/master/phablytics/web/metrics/forms.py#L43

**Comment by Justintime50** [comment]
@jontsai had a chance to check this out?

**Comment by jontsai** [comment]
I wasn't able to reproduce it exactly, but I think #11 handles this issue, hopefully.
